# Generated by Django 5.1.6 on 2025-02-18 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Userss',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=12)),
                ('created_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=250)),
                ('created_at', models.DateField()),
                ('conversation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_by_2user', to='Chats.conversations')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chats.userss')),
            ],
        ),
        migrations.AddField(
            model_name='conversations',
            name='user1_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_user1', to='Chats.userss'),
        ),
        migrations.AddField(
            model_name='conversations',
            name='user2_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_user2', to='Chats.userss'),
        ),
    ]
