# Generated by Django 5.1.6 on 2025-02-18 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userss',
            name='active_chat',
            field=models.BooleanField(default=False),
        ),
    ]
